//test
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cattle.io/timestamp: "2020-04-07T01:45:50Z"
    cni.projectcalico.org/podIP: 10.42.1.27/32
    cni.projectcalico.org/podIPs: 10.42.1.27/32
    field.cattle.io/ports: '[null]'
  creationTimestamp: null
  generateName: apache-85f65d4f5d-
  labels:
    pod-template-hash: 85f65d4f5d
    workload.user.cattle.io/workloadselector: deployment-apache2-apache
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: apache-85f65d4f5d
    uid: 08608e31-c619-4531-b542-229460589f93
  selfLink: /api/v1/namespaces/apache2/pods/apache-85f65d4f5d-vmgk2
spec:
  containers:
  - image: ubuntu
    imagePullPolicy: Always
    name: apache
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: false
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-cx6t9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: work2
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-cx6t9
    secret:
      defaultMode: 420
      secretName: default-token-cx6t9
status:
  phase: Pending
  qosClass: BestEffort
